version: '3.8'

services:
  backend:
    build:
      context: ./todo-backend
    volumes:
      - ./todo-backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  frontend:
    build:
      context: ./todo-frontend
    volumes:
      - ./todo-frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
