version: '3.8'

services:
  backend:
    build:
      context: ./todo-backend
    volumes:
      - ./todo-backend:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./todo-frontend
    volumes:
      - ./todo-frontend:/app
    ports:
      - "5174:5174"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
